services:
  spai-app:
    build: .
    container_name: spai-ui
    ports:
      - "8502:8502"
    volumes:
      # Mount the weights folder so you don't have to rebuild the image when adding weights
      - ./weights:/app/weights
      # Optional: Mount local source code for development
      # - ./spai:/app/spai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true